barter_platform/ads/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index_page, name="index"),
    path("ad_list/", views.ads_page, name='ads_list'),
    path("create_ad/", views.create_ad, name='create_ad'),
    path('<int:pk>/edit/', views.edit_ad, name='edit_ad'),
    path('index/', views.index_page, name='index_page'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('<int:pk>/delete_ad/', views.delete_ad, name='delete_ad'),
    path('create_proposal/', views.create_proposal, name='create_proposal'),
    path('proposals_list/', views.proposal_page, name='proposals_list'),
    path('<int:pk>/ad_detail/', views.ad_detail, name='ad_detail'),
    path('<int:pk>/proposals/set-status/<str:status>/', views.update_proposal_status, name='update_proposal_status'),

]

barter_platform/barter_platform/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ads/', include('ads.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

barter_platform/ads/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Ad(models.Model):
    CATEGORY_CHOICES = [
        ('toys', 'Игрушки'),
        ('electronics', 'Электроника'),
        ('sports', 'Товары для спорта'),
        ('home', 'Товары для дома'),
        ('books', 'Книги и журналы'),
        ('clothes', 'Одежда'),
        ('other', 'Другое')
    ]

    CONDITION_CHOICES = [
        ('new', 'Новый'),
        ('used', 'Б/у')
    ]

    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             default=None,
                             verbose_name='Пользователь')

    title = models.CharField(max_length=100,
                             verbose_name='Название')

    description = models.TextField(max_length=1000,
                                   verbose_name='Описание')

    image_url = models.ImageField(upload_to="images/",
                                blank=True,
                                null=True,
                                verbose_name='Фото')

    category = models.CharField(max_length=20,
                                choices=CATEGORY_CHOICES,
                                verbose_name='Категория')

    condition = models.CharField(max_length=10,
                                 choices=CONDITION_CHOICES,
                                 verbose_name='Состояние')

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class ExchangeProposal(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             default=None,
                             verbose_name='Пользователь')
    ad_sender = models.ForeignKey(Ad, on_delete=models.CASCADE,
                                  verbose_name='Предлагаемая вещь',
                                  related_name='sent_proposals',
                                  default=None)

    ad_receiver = models.ForeignKey(Ad, on_delete=models.CASCADE,
                                    verbose_name='Желаемая вещь',
                                    related_name='received_proposals',
                                    default=None)
    comment = models.CharField(max_length=200,
                               verbose_name='Комментарий')

    choices = [
        ('W', 'Ожидает'),
        ('Y', 'Принято'),
        ('N', 'Отклонено'),
    ]
    status = models.CharField(choices=choices, default='Ожидает',
                              verbose_name='Статус')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

barter_platform/ads/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from ads.models import Ad, ExchangeProposal
from django.contrib.auth.models import User


class AdForm(ModelForm):
    class Meta:
        model = Ad
        fields = ['title', 'description', 'image_url', 'category', 'condition']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class ExchangeForm(forms.ModelForm):
    class Meta:
        model = ExchangeProposal
        fields = ['ad_sender', 'ad_receiver', 'comment']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

        self.fields['ad_sender'].queryset = Ad.objects.filter(user=user)

        self.fields['ad_receiver'].queryset = Ad.objects.exclude(user=user)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class AuthForm(UserCreationForm):
    username = forms.CharField(required=True, label='Имя пользователя')
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=True, label='Имя')
    last_name = forms.CharField(max_length=30, required=True, label='Фамилия')

    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(label='Подтвердите пароль',
                                widget=forms.PasswordInput, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user


class LoginForm(ModelForm):
    username = forms.CharField(required=True, label='Имя пользователя')
    password = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput, required=True)

    class Meta:
        model = User
        fields = ['username', 'password']

barter_platform/ads/views.py
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect, get_object_or_404
from ads.models import Ad, ExchangeProposal
from django.contrib.auth.decorators import login_required
from ads.forms import AdForm, AuthForm, LoginForm, ExchangeForm
from django.db.models import Q
from django.core.paginator import Paginator


def index_page(request):
    return render(request, 'ads/index.html')


def ads_page(request):
    all_ads = Ad.objects.all()
    category = request.GET.get('category')
    condition = request.GET.get('condition')
    search_query = request.GET.get('q', '')

    if category:
        all_ads = all_ads.filter(category=category)

    if condition:
        all_ads = all_ads.filter(condition=condition)

    if search_query:
        all_ads = all_ads.filter(
            Q(title__icontains=search_query) | Q(description__icontains=search_query)
        )

    paginator = Paginator(all_ads, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'ads/ad_list.html', {
        'page_obj': page_obj,
        'category': category,
        'condition': condition,
        'search_query': search_query,
    })


def proposal_page(request):
    proposals = ExchangeProposal.objects.select_related('user', 'ad_sender', 'ad_receiver', 'ad_receiver__user')

    status = request.GET.get('status')
    sender_id = request.GET.get('sender', '')
    receiver_id = request.GET.get('receiver', '')

    if status:
        proposals = proposals.filter(status=status)

    if sender_id:
        proposals = proposals.filter(user__id=sender_id)

    if receiver_id:
        proposals = proposals.filter(ad_receiver__user__id=receiver_id)

    return render(request, 'ads/proposals_list.html', {
        'proposals': proposals,
        'status': status,
        'sender_id': sender_id,
        'receiver_id': receiver_id,
    })


@login_required
def create_ad(request):
    if request.method == 'POST':
        form = AdForm(request.POST, request.FILES)
        if form.is_valid():
            ad = form.save(commit=False)
            ad.user = request.user
            ad.save()
            return redirect('ads_list')
    else:
        form = AdForm()
    return render(request, 'ads/create_ad.html', {'form': form})


@login_required
def create_proposal(request):
    if request.method == 'POST':
        form = ExchangeForm(request.POST, user=request.user)  # передаём user
        if form.is_valid():
            proposal = form.save(commit=False)
            proposal.user = request.user
            proposal.status = 'W'
            proposal.save()
            return redirect('proposals_list')
    else:
        form = ExchangeForm(user=request.user)

    return render(request, 'ads/create_proposal.html', {'form': form})


@login_required
def update_proposal_status(request, pk, status):
    proposal = get_object_or_404(ExchangeProposal, pk=pk)
    if proposal.ad_receiver.user != request.user:
        return redirect('proposals_list')
    if status in ['Y', 'N']:
        proposal.status = status
        proposal.save()
    return redirect('proposals_list')


def ad_detail(request, pk):
    ad = get_object_or_404(Ad, pk=pk)
    return render(request, 'ads/ad_detail.html', {'ad': ad})


@login_required()
def edit_ad(request, pk):
    ad = get_object_or_404(Ad, pk=pk)

    if ad.user != request.user:
        messages.error(request, 'Вы можете редактировать только свои объявления')
        return redirect('ads_list')

    if request.method == 'POST':
        form = AdForm(request.POST, request.FILES, instance=ad)
        if form.is_valid():
            form.save()
            messages.success(request, 'Объявление успешно обновлено!')
            return redirect('ads_list')
    else:
        form = AdForm(instance=ad)

    return render(request, 'ads/edit_ad.html', {'form': form, 'ad': ad})


@login_required()
def delete_ad(request, pk):
    ad = Ad.objects.get(pk=pk)

    if ad.user != request.user:
        messages.error(request, 'Вы можете удалять только свои объявления.')
        return redirect('ads_list')
    else:
        ad.delete()
        messages.success(request, 'Объявление успешно удалено.')
        return redirect('ads_list')


def register(request):
    if request.method == 'POST':
        form = AuthForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Регистрация прошла успешно!')
            return redirect('ads_list')
    else:
        form = AuthForm()
    return render(request, 'ads/registration/register.html', {'form': form})


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Вы вошли!')
            return redirect('ads_list')
        else:
            messages.error(request, 'Неправильный логин или пароль.')
            return redirect('login')
    else:
        form = LoginForm()
    return render(request, 'ads/registration/login.html', {'form': form})


def logout_user(request):
    logout(request)
    messages.success(request, 'Вы вышли из аккаунта.')
    return redirect('ads_list')

barter_platform/templates/ads/ad_detail.html
{% extends 'ads/index.html' %}

{% block title %}{{ ad.title }}{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8">
            <div class="card shadow-sm border-0">
                {% if ad.image_url %}
                    <img src="{{ ad.image_url.url }}" class="card-img-top" alt="{{ ad.title }}"
                         style="max-height: 400px; object-fit: cover;">
                {% else %}
                    <div class="card-img-top d-flex align-items-center justify-content-center bg-light text-muted"
                         style="height: 300px;">
                        <i class="bi bi-image fs-1"></i>
                    </div>
                {% endif %}

                <div class="card-body">
                    <h2 class="card-title">{{ ad.title }}</h2>

                    <p class="text-muted">
                        Размещено {{ ad.created_at|date:"d.m.Y H:i" }} пользователем {{ ad.user.username }}
                    </p>

                    <div class="mb-3">
                        <span class="badge bg-light text-dark me-2">
                            {{ ad.get_category_display }}
                        </span>
                        <span class="badge bg-light text-dark">
                            {{ ad.get_condition_display }}
                        </span>
                    </div>

                    <p class="card-text fs-5">
                        {{ ad.description }}
                    </p>
                </div>

                <div class="card-footer bg-transparent d-flex justify-content-between">
                    <a href="{% url 'ads_list' %}" class="btn btn-outline-secondary">
                        ← Назад к объявлениям
                    </a>

                    {% if user.is_authenticated and user != ad.user %}
                        <a href="#" class="btn btn-primary">
                            Обменяться
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

barter_platform/templates/ads/ad_list.html
{% extends 'ads/index.html' %}

{% block title %}Все объявления{% endblock %}

{% block content %}
<form method="get" class="row row-cols-lg-auto g-3 align-items-end mb-4">
    <div class="col">
        <label for="category" class="form-label">Категория</label>
        <select name="category" id="category" class="form-select">
            <option value="">Все</option>
            <option value="toys" {% if category  == 'toys' %}selected{% endif %}>Игрушки</option>
            <option value="electronics" {% if category == 'electronics' %}selected{% endif %}>Электроника</option>
            <option value="sports" {% if category == 'sports' %}selected{% endif %}>Товары для спорта</option>
            <option value="home" {% if category == 'home' %}selected{% endif %}>Товары для дома</option>
            <option value="books" {% if category == 'books' %}selected{% endif %}>Книги</option>
            <option value="clothes" {% if category == 'clothes' %}selected{% endif %}>Одежда</option>
        </select>
    </div>

    <div class="col">
        <label for="condition" class="form-label">Состояние</label>
        <select name="condition" id="condition" class="form-select">
            <option value="">Все</option>
            <option value="new" {% if condition == 'new' %}selected{% endif %}>Новый</option>
            <option value="used" {% if condition == 'used' %}selected{% endif %}>Б/у</option>

        </select>
    </div>

    <div class="col">
        <label for="search" class="form-label">Поиск</label>
        <input type="text" name="q" id="search" class="form-control" placeholder="Поиск по названию или описанию"
               value="{{ search_query }}">
    </div>

    <div class="col">
        <button type="submit" class="btn btn-primary">Найти</button>
    </div>
</form>


<div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="mb-0">Все объявления</h1>
    {% if user.is_authenticated %}
        <a href="{% url 'create_ad' %}" class="btn btn-primary">
            <i class="bi bi-plus-circle me-1"></i>
            Создать объявление
        </a>
    {% endif %}
</div>

<div class="row g-4">
    {% for ad in page_obj %}
        <div class="col-12 col-md-6 col-lg-4">
            <div class="card h-100 border-0 shadow-sm">
                {% if ad.image_url %}
                    <img src="{{ ad.image_url.url }}"
                         alt="{{ ad.title }}"
                         class="card-img-top"
                         style="height: 200px; object-fit: cover;">
                {% else %}
                    <div class="card-img-top d-flex align-items-center justify-content-center bg-light text-muted"
                         style="height: 200px;">
                        <i class="bi bi-image fs-1"></i>
                    </div>
                {% endif %}

                <div class="card-body d-flex flex-column">

                    <h3 class="card-title">{{ ad.title }}</h3>

                </div>

                <div class="card-footer bg-transparent border-top">
                    <div class="d-flex justify-content-between align-items-center">
                        <small class="text-muted">
                            {{ ad.user.username }} • {{ ad.created_at|date:"d.m.Y" }}
                        </small>
                        <div class="btn-group btn-group-sm">
                            <a href="{% url 'ad_detail' ad.pk %}" class="btn btn-outline-secondary">
                                Подробнее
                            </a>
                            {% if user.is_authenticated and user == ad.user %}
                                <a href="{% url 'edit_ad' ad.pk %}" class="btn btn-outline-secondary">
                                    <i class="bi bi-pencil"></i>
                                </a>
                                <a href="{% url 'delete_ad' ad.pk %}" class="btn btn-outline-danger">
                                    <i class="bi bi-trash"></i>
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% empty %}
        <div class="col-12">
            <div class="text-center py-5">
                <i class="bi bi-inbox display-1 text-muted mb-3"></i>
                <h3 class="text-muted">Объявлений пока нет</h3>
                <p class="text-muted mb-4">Станьте первым, кто создаст объявление!</p>
                {% if user.is_authenticated %}
                    <a href="{% url 'create_ad' %}" class="btn btn-primary">
                        <i class="bi bi-plus-circle me-1"></i>
                        Создать объявление
                    </a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
</div>

<nav class="mt-4">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?{% if search_query %}q={{ search_query }}&{% endif %}{% if category %}category={{ category }}&{% endif %}{% if condition %}condition={{ condition }}&{% endif %}page={{ page_obj.previous_page_number }}">← Назад</a>
      </li>
    {% endif %}

    <li class="page-item disabled">
      <span class="page-link">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?{% if search_query %}q={{ search_query }}&{% endif %}{% if category %}category={{ category }}&{% endif %}{% if condition %}condition={{ condition }}&{% endif %}page={{ page_obj.next_page_number }}">Вперёд →</a>
      </li>
    {% endif %}
  </ul>
</nav>

{% endblock %}

barter_platform/templates/ads/create_ad.html
{% extends 'ads/index.html' %}

{% block content %}
<div class="container mt-5" style="max-width: 600px;">
    <h2 class="mb-4 text-center">Создать новое объявление</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary mt-3">Сохранить</button>
    </form>
</div>
{% endblock %}

barter_platform/templates/ads/create_proposal.html
{% extends 'ads/index.html' %}

{% block content %}
<div class="container mt-5" style="max-width: 600px;">
    <h2 class="mb-4 text-center">Предложить новое обмен</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary mt-3">Отправить</button>
    </form>
</div>
{% endblock %}

barter_platform/templates/ads/delete_ad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Удаление объявления</title>
</head>
<body>

</body>
</html>

barter_platform/templates/ads/edit_ad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Редактирование объявления</title>
</head>
<body>
    {% extends 'ads/index.html' %}

    {% block content %}

    <h1></h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>

    {% endblock %}
</body>
</html>

barter_platform/templates/ads/proposals_list.html
{% extends 'ads/index.html' %}

{% block title %}Предложения об обмене{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4 text-center">Предложения об обмене</h2>

    <form method="get" class="row row-cols-lg-auto g-3 align-items-end mb-4">
        <div class="col">
            <label class="form-label">Статус</label>
            <select name="status" class="form-select">
                <option value="">Все</option>
                <option value="W" {% if status == 'W' %}selected{% endif %}>Ожидает</option>
                <option value="Y" {% if status == 'Y' %}selected{% endif %}>Принято</option>
                <option value="N" {% if status == 'N' %}selected{% endif %}>Отклонено</option>
            </select>
        </div>

        <div class="col">
            <label class="form-label">Отправитель (ID)</label>
            <input name="sender" type="text" class="form-control" value="{{ sender_id }}">
        </div>

        <div class="col">
            <label class="form-label">Получатель (ID)</label>
            <input name="receiver" type="text" class="form-control" value="{{ receiver_id }}">
        </div>

        <div class="col">
            <button type="submit" class="btn btn-primary">Фильтровать</button>
        </div>
    </form>

    {% if proposals %}
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for proposal in proposals %}
        <div class="col">
            <div class="card shadow-sm h-100">
                <div class="card-body d-flex flex-column">

                    <h5 class="card-title">
                        От: <strong>{{ proposal.user.username }}</strong><br>
                        Кому: <strong>{{ proposal.ad_receiver.user.username }}</strong>
                    </h5>

                    <p><strong>Он предлагает:</strong> {{ proposal.ad_sender.title }}</p>
                    <p><strong>Хочет получить:</strong> {{ proposal.ad_receiver.title }}</p>

                    {% if proposal.comment %}
                        <p class="text-muted mt-2"><em>"{{ proposal.comment }}"</em></p>
                    {% endif %}


                    <span class="badge
                        {% if proposal.status == 'Y' %} bg-success
                        {% elif proposal.status == 'N' %} bg-danger
                        {% else %} bg-warning text-dark
                        {% endif %}">
                        {{ proposal.get_status_display }}
                    </span>


                    {% if user == proposal.ad_receiver.user and proposal.status == 'W' %}
                        <div class="mt-3 d-flex gap-2">
                            <a href="{% url 'update_proposal_status' proposal.pk 'Y' %}"
                               class="btn btn-success btn-sm">Принять</a>
                            <a href="{% url 'update_proposal_status' proposal.pk 'N' %}"
                               class="btn btn-danger btn-sm">Отклонить</a>
                        </div>
                    {% endif %}

                    <p class="mt-3 text-end text-muted small">
                        {{ proposal.created_at|date:"d.m.Y H:i" }}
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
        <div class="text-center py-5">
            <i class="bi bi-inbox display-1 text-muted mb-3"></i>
            <h3 class="text-muted">Нет предложений</h3>
            <p class="text-muted mb-4">Попробуйте изменить фильтры.</p>
        </div>
    {% endif %}
</div>
{% endblock %}